[package]
name = "staging-xcm-builder"
description = "Tools & types for building with XCM and its executor. (polkadot v1.15.0)"
authors.workspace = true
edition.workspace = true
license.workspace = true
version = "16.0.3"

[lints]
workspace = true

[dependencies]
<<<<<<< HEAD
=======
codec = { features = ["derive"], workspace = true }
environmental = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
>>>>>>> bd7cf119 (XCM: Deny barrier checks for nested XCMs with specific instructions to be executed on the local chain (#7200))
impl-trait-for-tuples = { workspace = true }
codec = { features = ["derive"], workspace = true }
scale-info = { features = ["derive"], workspace = true }
<<<<<<< HEAD
xcm.workspace = true
xcm-executor.workspace = true
sp-arithmetic.workspace = true
sp-io.workspace = true
sp-runtime.workspace = true
sp-weights.workspace = true
frame-support.workspace = true
frame-system.workspace = true
pallet-transaction-payment.workspace = true
log = { workspace = true }
polkadot-parachain-primitives.workspace = true

[dev-dependencies]
primitive-types = { workspace = true, default-features = true }
pallet-balances = { default-features = true, path = "../../../substrate/frame/balances" }
pallet-xcm = { default-features = true, path = "../pallet-xcm" }
pallet-salary = { default-features = true, path = "../../../substrate/frame/salary" }
pallet-assets = { default-features = true, path = "../../../substrate/frame/assets" }
polkadot-primitives = { default-features = true, path = "../../primitives" }
polkadot-runtime-parachains = { default-features = true, path = "../../runtime/parachains" }
assert_matches = { workspace = true }
polkadot-test-runtime = { path = "../../runtime/test-runtime" }
=======
sp-arithmetic = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-weights = { workspace = true }
xcm = { workspace = true }
xcm-executor = { workspace = true }

# Polkadot dependencies
polkadot-parachain-primitives = { workspace = true }

[dev-dependencies]
pallet-assets = { workspace = true, default-features = true }
pallet-balances = { workspace = true, default-features = true }
pallet-salary = { workspace = true, default-features = true }
pallet-xcm = { workspace = true, default-features = true }
polkadot-primitives = { workspace = true, default-features = true }
polkadot-runtime-parachains = { workspace = true, default-features = true }
polkadot-test-runtime = { workspace = true }
primitive-types = { features = ["codec", "num-traits", "scale-info"], workspace = true }
>>>>>>> bd7cf119 (XCM: Deny barrier checks for nested XCMs with specific instructions to be executed on the local chain (#7200))

[features]
default = ["std"]
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"polkadot-parachain-primitives/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
]
std = [
	"codec/std",
	"environmental/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"pallet-transaction-payment/std",
	"polkadot-parachain-primitives/std",
	"scale-info/std",
	"sp-arithmetic/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-weights/std",
	"xcm-executor/std",
	"xcm/std",
]
