[relaychain]
default_image = "parity/polkadot:latest"
default_command = "polkadot"
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
validator = true
args = ["-laura=trace,parachain=debug,parachain::collator-protocol=trace,parachain::subsystem-util=trace"]

[[relaychain.nodes]]
name = "bob"
validator = true
args = ["-laura=trace,parachain=debug,parachain::collator-protocol=trace,parachain::subsystem-util=trace"]

[[parachains]]
id = 2000
cumulus_based = true
chain = "asset-hub-rococo-local"

# run charlie as parachain collator
[[parachains.collators]]
name = "charlie"
validator = true
image = "parity/polkadot-parachain:latest"
command = "polkadot-parachain"
args = ["--force-authoring", "--experimental-use-slot-based", "-laura=trace,parachain=debug,parachain::collator-protocol=trace,parachain::subsystem-util=trace"]

[[parachains.collators]]
name = "dave"
validator = true
image = "parity/polkadot-parachain:latest"
command = "polkadot-parachain"
args = ["--force-authoring", "--experimental-use-slot-based", "-laura=trace,parachain=debug,parachain::collator-protocol=trace,parachain::subsystem-util=trace"]
