[package]
name = "staging-xcm"
<<<<<<< HEAD
description = "The basic XCM datastructures. (polkadot v1.15.0)"
version = "14.1.0"
=======
description = "The basic XCM datastructures."
version = "7.0.1"
>>>>>>> 963f0d73 (Fix DryRunApi client-facing XCM versions (#7438))
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
array-bytes = { workspace = true, default-features = true }
bounded-collections = { features = ["serde"], workspace = true }
derivative = { features = ["use_core"], workspace = true }
impl-trait-for-tuples = { workspace = true }
log = { workspace = true }
codec = { features = ["derive", "max-encoded-len"], workspace = true }
scale-info = { features = ["derive", "serde"], workspace = true }
sp-weights = { features = ["serde"], workspace = true }
serde = { features = ["alloc", "derive", "rc"], workspace = true }
schemars = { default-features = true, optional = true, workspace = true }
xcm-procedural.workspace = true
xcm-procedural.default-features = true
environmental = { workspace = true }

[dev-dependencies]
sp-io = { default-features = true, path = "../../substrate/primitives/io" }
hex = { workspace = true, default-features = true }
hex-literal = { workspace = true, default-features = true }

[features]
default = ["std"]
wasm-api = []
std = [
	"bounded-collections/std",
	"codec/std",
	"environmental/std",
	"log/std",
	"scale-info/std",
	"serde/std",
	"sp-weights/std",
]
json-schema = ["bounded-collections/json-schema", "dep:schemars", "sp-weights/json-schema"]
