[relaychain]
# single-state
# fork-aware
default_image = "parity/polkadot:latest"
default_command = "polkadot"
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  ws_port = 9944
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

[[parachains]]
id = 2000
cumulus_based = true
# chain = "asset-hub-rococo-local.json"
# chain = "asset-hub-rococo-local-20k.json"
chain = "yap-westend-live-2022.json"

  # run charlie as parachain collator
  [[parachains.collators]]
  name = "charlie"
  validator = true
  image = "parity/polkadot-parachain:latest"
  command = "polkadot-parachain"
  # command = "test-parachain"
  ws_port = 9933
  rpc_port = 8833
  args = [
    "--pool-limit 500000",
    "--pool-kbytes 2048000",
    "--rpc-max-connections 15000",
    "--rpc-max-response-size 150",
    "-lbasic-authorship=info",
    "-ltxpool=debug",
    "-lsync=info",
    "-laura::cumulus=info",
    "-lpeerset=info",
    "-lsub-libp2p=info",
    # "-lexecutor=trace",
    # "-lwasm-executor=trace",
    # "-lwasm-runtime=trace",
    "--pool-type=fork-aware",
    "--experimental-use-slot-based",
    "--rpc-max-subscriptions-per-connection=128000",
    "--max-runtime-instances=32",
  ]

